- name: install centos-release-opstools
  yum:
    name: centos-release-opstools
    state: present
  become: true
  when: ansible_distribution == 'CentOS'

- name: install collectd and dependencies
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - collectd
    - collectd-python
    - python-pip

- name: install sqlalchemy-collectd on undercloud
  shell: pip install git+http://github.com/sqlalchemy/sqlalchemy-collectd
  become: true

- name: setup conf
  template:
    src: sqlalchemy.conf.j2
    dest: /etc/collectd.d/sqlalchemy.conf
  become: true

- name: setup firewall
  lineinfile:
    path: /etc/sysconfig/iptables
    line: "-A INPUT -p udp  --dport 25827 -j ACCEPT"
    insertafter: "-A INPUT .* --dports? 22"
  become: true

- name: restart iptables
  systemd:
    name: iptables
    state: restarted
  become: true


