- name: install collectd and dependencies
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - collectd
    - collectd-python
    - python-pip

- name: install sqlalchemy-collectd on undercloud
  shell: pip install git+http://github.com/sqlalchemy/sqlalchemy-collectd
  become: true

- name: setup conf
  template:
    src: sqlalchemy.conf.j2
    dest: /etc/collect.d/sqlalchemy.conf
