- name: install collectd in containers
  shell:
    docker exec -it {{ item }} pip install http://github.com/sqlalchemy/sqlalchemy_collectd
  become: yes
  with_items:
    - nova_api
    - nova_placement
    - nova_metadata
    - keystone
    - keystone_cron
    - cinder_api
    - cinder_api_cron
    - cinder_scheduler
    - neutron_api
    - neutron_l3_agent
    - neutron_ovs_agent
    - neutron_metadata_agent

- name: change DB url in conf files
  lineinfile:
    path: "{{ item }}"
    regexp: '^(connection=mysql\+pymysql://.*)$'
    line: '\1&plugin=collectd&collectd_host={{ undercloud_ip }}'
    backrefs: yes
    backup: yes
  become: yes
  with_items:
    - "/var/lib/config-data/puppet-generated/keystone/etc/keystone/keystone.conf"
    - "/var/lib/config-data/puppet-generated/nova/etc/nova/nova.conf"
    - "/var/lib/config-data/puppet-generated/neutron/etc/neutron/neutron.conf"
    - "/var/lib/config-data/puppet-generated/cinder/etc/cinder/cinder.conf"

