- name: setup collectd on undercloud
  hosts:
    - undercloud
  roles:
    - { role: setup-collectd, tags: ['setup_collectd'] }

- name: setup overcloud services
  hosts:
    - overcloud
  roles:
    - { role: assign-plugin, tags: ['assign_plugin'] }



